name: Publish

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        default: 'production'
        required: false
        type: string
      GENERATE_CLIENT:
        default: false
        required: false
        type: boolean
    secrets:
      PUBLISH_PACKAGES:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with personal token
        uses: actions/checkout@v2
        env:
          GENERATE_CLIENT: ${{ inputs.GENERATE_CLIENT }}
        if: ${{ env.GENERATE_CLIENT == 'true' }}
        with:
          fetch-depth: 0
          token: ${{ secrets.PUBLISH_PACKAGES }}

      - name: Checkout
        uses: actions/checkout@v2
        env:
          GENERATE_CLIENT: ${{ inputs.GENERATE_CLIENT }}
        if: ${{ env.GENERATE_CLIENT == 'false' }}
        with:
          fetch-depth: 0

      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2

      - name: Setup npm
        run: |
          npm set @candisio:registry=https://npm.pkg.github.com/candisio
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.PUBLISH_PACKAGES }}"

      - name: Install dependencies
        run: |
          npm install && npm i lerna ts-node tsconfig-paths -g
          lerna bootstrap

      - name: Generate new client
        env:
          GENERATE_CLIENT: ${{ inputs.GENERATE_CLIENT }}
        if: ${{ env.GENERATE_CLIENT == 'true' }}
        run: |
          npm run build
          ts-node -r tsconfig-paths/register ./node_modules/@candisio/common/lib/cli.js generate-swagger --appModuleSrc=/src/app.module.ts && cd ./packages/sdk && npm run oapi-generate

      - name: "Version and publish"
        env:
          GH_TOKEN: ${{ secrets.PUBLISH_PACKAGES }}
          ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          if [ "$ENVIRONMENT" == "production" ]
          then
            git diff-index --quiet HEAD || git add ./packages && git commit -m "feat: updated packages [skip ci]" && git push
            lerna version --conventional-commits --yes
            lerna run tsc
            lerna publish from-git --yes
          else
            git diff-index --quiet HEAD || git add ./packages && git commit -m "feat: updated canary packages [skip ci]"
            lerna run tsc
            lerna publish from-git --yes --canary
          fi
