name: Publish

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        default: 'production'
        required: false
        type: string
      GENERATE_CLIENT:
        default: false
        required: false
        type: boolean
    secrets:
      PUBLISH_PACKAGES:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PUBLISH_PACKAGES }}
          GITHUB_TOKEN: ${{ github.token }}
          GENERATE_CLIENT: ${{ inputs.GENERATE_CLIENT }}
        with:
          fetch-depth: 0
          token: ${{ $([[ "GENERATE_CLIENT" == "true" ]] && echo $PERSONAL_TOKEN || echo $GITHUB_TOKEN) }}

      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2

      - name: Setup npm
        run: |
          npm set @candisio:registry=https://npm.pkg.github.com/candisio
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.PUBLISH_PACKAGES }}"

      - name: Install dependencies
        run: |
          npm install && npm i lerna @candisio/common -g
          lerna bootstrap

      - name: Generate new client
        env:
          GENERATE_CLIENT: ${{ inputs.GENERATE_CLIENT }}
        if: ${{ env.GENERATE_CLIENT == 'true' }}
        run: |
          @candisio/common generate-swagger && cd ./packages/sdk && npm run oapi-generate

      - name: "Version and publish"
        env:
          GH_TOKEN: ${{ secrets.PUBLISH_PACKAGES }}
          ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          git diff-index --quiet HEAD || git add ./packages && git commit -m "feat: updated packages [skip ci]" && git push

          lerna run tsc

          if [ "$ENVIRONMENT" == "production" ]
          then
            lerna publish from-git --yes
            lerna version --conventional-commits --yes
          else
            lerna publish from-git --yes --canary
          fi
